// ─── usePortfolioDNA — hydrates the PS DNA profile JSON once at mount ───
// The profile lives at /ps-dna-profile.json (public/) and is generated by
// scripts/ps-dna-build-profile.mjs. Returns { dna, loading, error }.
//
// Used by App.js to power the Portfolio Fit badge and analytics view.
// Falls back gracefully if the profile is missing — the UI just hides
// the badge and the REC Package skips the section.

import { useEffect, useState } from 'react';

let _cachedDNA = null;

export function usePortfolioDNA() {
  const [dna, setDna] = useState(_cachedDNA);
  const [loading, setLoading] = useState(!_cachedDNA);
  const [error, setError] = useState(null);

  useEffect(() => {
    if (_cachedDNA) return;
    let cancelled = false;
    fetch('/ps-dna-profile.json', { cache: 'force-cache' })
      .then(r => {
        if (!r.ok) throw new Error(`HTTP ${r.status}`);
        return r.json();
      })
      .then(json => {
        if (cancelled) return;
        _cachedDNA = json;
        setDna(json);
        setLoading(false);
      })
      .catch(e => {
        if (cancelled) return;
        console.warn('PS DNA profile not loaded:', e.message);
        setError(e.message);
        setLoading(false);
      });
    return () => { cancelled = true; };
  }, []);

  return { dna, loading, error };
}
