// ─── PortfolioFit™ Scoring Engine — PS DNA Benchmark ───
//
// Additive second lens to SiteScore. Where SiteScore answers "is this a
// good site on its own merits?", PortfolioFit answers "is this the kind
// of site PS actually buys?" by benchmarking the candidate against the
// real demographic distributions of PS's 4,639 family locations
// (PS-owned + iStorage + NSA, the PS family per CLAUDE.md §6b).
//
// PHILOSOPHY — bell-curve fit:
// PS's existing portfolio represents their preferred zone. Sites in the
// bulk of the distribution (P25-P75 of the relevant sub-profile) score
// highest — they look like typical PS purchases. Edges of the
// distribution score lower — they're outside what PS routinely buys.
//
// Sub-profiles by submarket density (from 3-mi population):
//   urban:    pop >=  80,000
//   suburban: pop  25,000 – 80,000
//   exurban:  pop   5,000 – 25,000
//   rural:    pop <   5,000
//
// This is ADDITIVE to SiteScore — never modify scoring.js. The two
// scores are designed to be read side-by-side. A site can be SiteScore
// PRIME but PortfolioFit POOR (great deal, wrong DNA), or vice versa.

let _dnaCache = null;

// Lazy-load DNA profile from public/. The profile is generated by
// scripts/ps-dna-build-profile.mjs and committed to public/ so it's
// available at runtime without a Firebase fetch.
async function loadDNA() {
  if (_dnaCache) return _dnaCache;
  try {
    const res = await fetch('/ps-dna-profile.json');
    if (!res.ok) throw new Error(`DNA profile fetch failed: ${res.status}`);
    _dnaCache = await res.json();
    return _dnaCache;
  } catch (e) {
    console.warn('PortfolioFit: DNA profile unavailable —', e.message);
    return null;
  }
}

// Sync version — caller passes the DNA object explicitly. Used by
// scripts and by App.js once the profile is hydrated into state.
export function classifyDensity(pop3mi) {
  const n = Number(pop3mi) || 0;
  if (n >= 80000) return 'urban';
  if (n >= 25000) return 'suburban';
  if (n >= 5000)  return 'exurban';
  return 'rural';
}

// Linear-interpolated percentile rank against a P10/P25/P50/P75/P90 dist.
// dist = { min, p10, p25, p50, p75, p90, max }
export function percentileRank(value, dist) {
  if (!dist || value == null || !isFinite(value)) return 50;
  if (value <= dist.min) return 0;
  if (value >= dist.max) return 100;
  const points = [
    [dist.min, 0], [dist.p10, 10], [dist.p25, 25], [dist.p50, 50],
    [dist.p75, 75], [dist.p90, 90], [dist.max, 100],
  ];
  for (let i = 1; i < points.length; i++) {
    if (value <= points[i][0]) {
      const [v0, p0] = points[i - 1];
      const [v1, p1] = points[i];
      if (v1 === v0) return p0;
      return p0 + ((value - v0) / (v1 - v0)) * (p1 - p0);
    }
  }
  return 100;
}

// Convert a percentile rank (0-100) to a 0-10 fit score.
// Bell-curve: P25-P75 = best fit (10), edges fall off symmetrically.
export function attributeFitScore(percentile) {
  if (percentile == null || !isFinite(percentile)) return 5;
  const p = percentile;
  if (p >= 25 && p <= 75) return 10;
  if (p >= 15 && p <= 85) return 8;
  if (p >= 10 && p <= 90) return 6;
  if (p >= 5  && p <= 95) return 4;
  return 2;
}

// Parse numeric field tolerating "$95,200", "4.5%", "12,400 (est.)", etc.
function parseNum(v) {
  if (v == null || v === '') return NaN;
  const s = String(v);
  const m = s.match(/-?[\d,.]+/);
  if (!m) return NaN;
  const n = parseFloat(m[0].replace(/,/g, ''));
  return isNaN(n) ? NaN : n;
}

// Default attribute weights — sum to 1.0. Tunable via DNA profile or
// site-level overrides. Calibrated against 10 wins / 10 passes in
// validation (Phase 4) — adjust if correlation is poor.
export const DEFAULT_PORTFOLIO_FIT_WEIGHTS = {
  population:  0.20,
  income:      0.18,
  growth:      0.15,
  households:  0.10,
  homeValue:   0.10,
  renterPct:   0.10,
  nearestPS:   0.17,
};

// Compute the PortfolioFitScore for a site against the DNA profile.
// Returns: { score, classification, classColor, density, attributes,
//   percentiles, weights, notes, dnaSubProfileSize }
export function computePortfolioFit(site, dna, weights = DEFAULT_PORTFOLIO_FIT_WEIGHTS) {
  if (!dna || !dna.subProfiles) {
    return {
      score: 0, classification: 'NO DNA', classColor: '#64748B',
      density: null, attributes: {}, percentiles: {}, weights,
      notes: 'DNA profile unavailable — run scripts/ps-dna-build-profile.mjs',
      dnaSubProfileSize: 0,
    };
  }

  const pop3mi = parseNum(site.pop3mi);
  const hhi3mi = parseNum(site.income3mi);
  const hh3mi = parseNum(site.households3mi);
  const homeVal3mi = parseNum(site.homeValue3mi);
  const growth = parseNum(site.growthRate || site.popGrowth3mi);
  const renterPct = parseNum(site.renterPct3mi);
  const nearestPS = parseNum(site.siteiqData?.nearestPS);

  if (!isFinite(pop3mi) || pop3mi === 0) {
    return {
      score: 0, classification: 'NO DATA', classColor: '#64748B',
      density: null, attributes: {}, percentiles: {}, weights,
      notes: 'Site lacks 3-mi population — cannot benchmark against DNA',
      dnaSubProfileSize: 0,
    };
  }

  const density = classifyDensity(pop3mi);
  const sub = dna.subProfiles[density];
  if (!sub || !sub.distributions) {
    return {
      score: 0, classification: 'NO DNA', classColor: '#64748B',
      density, attributes: {}, percentiles: {}, weights,
      notes: `No DNA sub-profile for density bucket "${density}"`,
      dnaSubProfileSize: 0,
    };
  }
  const d = sub.distributions;

  const safe = (v, dist) => isFinite(v) && dist ? percentileRank(v, dist) : null;
  const percentiles = {
    population: safe(pop3mi,    d.pop3mi),
    income:     safe(hhi3mi,    d.hhi3mi),
    growth:     safe(growth,    d.growth),
    households: safe(hh3mi,     d.households3mi),
    homeValue:  safe(homeVal3mi, d.homeValue3mi),
    renterPct:  safe(renterPct, d.renterPct),
    nearestPS:  safe(nearestPS, d.nearestSiblingMi),
  };

  const attributes = {};
  Object.entries(percentiles).forEach(([k, p]) => {
    attributes[k] = p == null ? null : attributeFitScore(p);
  });

  // Weighted composite — only count attributes with valid percentile.
  // Re-normalize weights against those that contributed.
  let weightedSum = 0, weightTotal = 0;
  Object.entries(attributes).forEach(([k, v]) => {
    if (v == null) return;
    const w = weights[k] || 0;
    weightedSum += v * w;
    weightTotal += w;
  });
  const score = weightTotal > 0 ? weightedSum / weightTotal : 0;

  let classification, classColor;
  if (score >= 8.0)      { classification = 'STRONG MATCH'; classColor = '#22C55E'; }
  else if (score >= 6.0) { classification = 'GOOD MATCH';   classColor = '#3B82F6'; }
  else if (score >= 4.0) { classification = 'OK MATCH';     classColor = '#F59E0B'; }
  else                   { classification = 'POOR MATCH';   classColor = '#EF4444'; }

  // Top 3 strongest contributors (highest scoring attributes)
  const sortedAttrs = Object.entries(attributes)
    .filter(([, v]) => v != null)
    .sort((a, b) => b[1] - a[1]);
  const topDrivers = sortedAttrs.slice(0, 3).map(([k]) => k);
  const weakDrivers = sortedAttrs.slice(-2).map(([k]) => k);

  const labelize = (k) => ({
    population: '3-mi pop', income: 'HHI', growth: 'growth',
    households: 'HH', homeValue: 'home value', renterPct: 'renter %',
    nearestPS: 'PS clustering',
  }[k] || k);

  const driversTxt = topDrivers.length
    ? `Strongest fit: ${topDrivers.map(labelize).join(', ')}`
    : '';
  const weakTxt = weakDrivers.length && score < 8.0
    ? ` · Weakest: ${weakDrivers.map(labelize).join(', ')}`
    : '';
  const notes = `${density.toUpperCase()} DNA bucket (${sub.count} PS sites). ${driversTxt}${weakTxt}`;

  return {
    score: Math.round(score * 100) / 100,
    classification,
    classColor,
    density,
    attributes,
    percentiles: Object.fromEntries(
      Object.entries(percentiles).map(([k, v]) => [k, v == null ? null : Math.round(v)])
    ),
    weights,
    notes,
    dnaSubProfileSize: sub.count,
  };
}

// Convenience wrapper for callers that hydrate DNA via fetch.
export async function computePortfolioFitAsync(site) {
  const dna = await loadDNA();
  return computePortfolioFit(site, dna);
}

// Used by ingestion scripts and by the App.js hydration effect to make
// DNA-aware scoring available without a per-site fetch.
export async function preloadDNA() {
  return loadDNA();
}

// Format a one-line blurb for use in latestNote / activity log.
// Example: "Portfolio Fit 7.6/10 GOOD MATCH (suburban DNA) — pop P52, HHI P64."
export function formatPortfolioFitBlurb(fit) {
  if (!fit || fit.classification === 'NO DATA' || fit.classification === 'NO DNA') {
    return null;
  }
  const p = fit.percentiles || {};
  const pieces = [];
  if (p.population != null) pieces.push(`pop P${p.population}`);
  if (p.income     != null) pieces.push(`HHI P${p.income}`);
  if (p.growth     != null) pieces.push(`growth P${p.growth}`);
  return `Portfolio Fit ${fit.score.toFixed(1)}/10 ${fit.classification} (${fit.density} DNA)${pieces.length ? ' — ' + pieces.slice(0, 2).join(', ') : ''}.`;
}
